package Codes;
import java.sql.*;

public class DatabaseExample {
    public static void main(String[] args) {
        String url = "jdbc:oracle:thin:@localhost:1521:xe"; 
        String user = "system"; 
        String password = "oracle"; 

        try (Connection conn = DriverManager.getConnection(url, user, password)) {
            System.out.println("Connected to Oracle DB.");

            String createTable = "CREATE TABLE students (" +
                                 "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                 "name VARCHAR2(50), " +
                                 "age NUMBER)";
            try (Statement stmt = conn.createStatement()) {
                stmt.executeUpdate(createTable);
            } catch (SQLException e) {
                System.out.println("Table may already exist.");
            }

            String insert = "INSERT INTO students(name, age) VALUES(?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(insert)) {
                pstmt.setString(1, "Suveer");
                pstmt.setInt(2, 23);
                pstmt.executeUpdate();

                pstmt.setString(1, "Rohan");
                pstmt.setInt(2, 21);
                pstmt.executeUpdate();
            }

            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM students");
            while (rs.next()) {
                System.out.println(rs.getInt("id") + " | " +
                                   rs.getString("name") + " | " +
                                   rs.getInt("age"));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
